# Stage 0: install deps and build
FROM node:24-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY ./ ./

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

# Stage 1: run
FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build-stage /app/package*.json ./
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/public ./public
COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/next.config.mjs ./

EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]

