"""Locust load test for the builder /chat endpoint and the commerce read paths.

COST SAFETY. Every request carries X-Palladium-Load-Test, which routes the turn
into stub LMs. See backend/app/core/loadtest.py. Without a matching
LOAD_TEST_SECRET on the server the header is ignored and the run makes REAL
OpenRouter calls, one per build step per simulated user. Two independent guards
exist so that cannot happen quietly:

  * a preflight in on_test_start, which refuses to start the run at all, and
  * a per-response check on every /chat call, which aborts the run mid-flight.

The second is not redundant. The preflight only proves the secret was good at
t=0; a rotation, a worker rollout onto an image without the stub, or a Pub/Sub
message that lost the flag would all start spending money after the run began.

THE WIRE FORMAT is assistant-transport, the same protocol the browser speaks:
the request carries `commands` (an `add-message` per user message) and the
response is a stream of `aui-state:` lines, each a JSON list of operations on
the conversation state. Assistant text arrives as `append-text` operations,
progress as `set` on ["pipeline"]. Blank lines are keepalives. This file used to
post `{"messages": [...]}` and read SSE `data:` frames, the protocol before the
transport rework, and every request got a 400 from that day on; the preflight
caught it, so nothing was spent, but nothing was tested either.

WHY IT LIVES HERE and not in scripts/: this file is mounted into the Locust
pods as a ConfigMap generated by ./kustomization.yaml, and kustomize refuses to
read files above its own directory. Keeping it beside the manifests is what
makes `kubectl apply -k deploy/loadtest` a single self-contained command.

Run in-cluster, the normal way:
    kubectl apply -k deploy/loadtest
    kubectl -n palladium port-forward svc/locust-master 8089:8089

Run locally against a dev server:
    LOAD_TEST_SECRET=... COMMERCE_URL=http://localhost:8080 \
      locust -f deploy/loadtest/locustfile.py --host http://localhost:8000
"""

from __future__ import annotations

import json
import logging
import os
import time
from enum import Enum, auto
from typing import Any

import gevent
import requests
from locust import HttpUser, between, events, task
from locust.runners import WorkerRunner

logger = logging.getLogger(__name__)

SECRET = os.environ.get("LOAD_TEST_SECRET", "")

# commerce is a second Service, so its calls go out as absolute URLs rather than
# through the user's base host. Deliberate: --host is what the web UI's Host
# field edits, and that field should mean "the builder deployment under test".
COMMERCE_URL = os.environ.get("COMMERCE_URL", "http://commerce").rstrip("/")

# "stubbed" is the first distinctive word of the stub's canned text
# (backend/app/core/loadtest_stubs.py). Matched against the reassembled reply,
# never a single operation: the stub streams word by word.
_STUB_MARKER = "stubbed"

# The DSPy stub's answer to every free-text field, and so the `reason` on each
# case option it picks. The other proof of stubbing, and the only one on the
# expensive path: a turn that runs the whole ladder pauses at the case picker
# with a fixed server sentence ("Your parts are picked out...",
# backend/app/services/graph/nodes.py) and no chat-model text at all. Without
# this, the cost guard read that sentence as a real model and aborted the run
# on exactly the turns a load test exists to drive. A real model never gives
# the one-word reason "stub".
_DSPY_STUB_REASON = "stub"

# The server's own fallback texts, from services/transport.py and
# services/turn_runner.py. These arrive as ordinary append-text operations, so
# without matching them explicitly a saturated backend is indistinguishable
# from a real model answering, and the cost guard would abort the run exactly
# when the load test got interesting. Matched on a distinctive fragment rather
# than the full string, which carries leading newlines and trailing
# punctuation.
_SERVICE_ERRORS = (
    "That build didn't start",
    "Lost the connection to the build service",
    "Something went wrong generating your recommendation",
)


class _Stream(Enum):
    """What produced a /chat stream. Drives cost safety, so it is explicit
    rather than a bool: "not the stub" covers both a free error message and an
    expensive real completion, and those are not the same event."""

    EMPTY = auto()  # no assistant text at all
    STUBBED = auto()  # the stub LM. The expected case
    SERVICE_ERROR = auto()  # a server fallback message; nothing was spent
    UNSTUBBED = auto()  # real model output; money is being spent


# Varied enough that profile extraction sees different inputs, short enough that
# the request body is not itself the thing being measured.
_PROMPTS = [
    "I want a gaming PC for about $1500",
    "Build me a video editing workstation under $2500",
    "Cheapest machine that can run local LLMs, budget $2000",
    "Quiet small-form-factor PC for software development, around $1200",
]

# Latches so an abort fires once rather than once per simulated user.
_aborted = False


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "X-Palladium-Load-Test": SECRET,
    }


def _turn_body(prompt: str) -> dict:
    """One new conversation's first turn, as the frontend's runtime sends it."""
    return {
        "conversation_id": None,
        "state": {"messages": [], "pipeline": None},
        "commands": [
            {
                "type": "add-message",
                "message": {
                    "role": "user",
                    "parts": [{"type": "text", "text": prompt}],
                },
            }
        ],
    }


def _abort(environment, message: str) -> None:
    """Stop the whole run, loudly, without spending anything further."""
    global _aborted
    if _aborted:
        return
    _aborted = True

    logger.critical("ABORTING LOAD TEST: %s", message)
    # Non-zero exit for headless/CI runs. Ignored by the web UI, harmless there.
    environment.process_exit_code = 1

    if environment.runner is None:
        return
    # Deferred by a greenlet rather than called inline: quit() tears down the
    # runner that is currently executing this handler, and doing that from
    # inside its own event dispatch deadlocks. spawn_later(0) runs it on the
    # next gevent turn, once the handler has returned.
    #
    # In-cluster this exits the master process and Kubernetes restarts the pod,
    # which comes back to an idle web UI. That is the intended outcome: no load
    # is running, and the reason is in `kubectl logs`.
    gevent.spawn_later(0, environment.runner.quit)


@events.test_start.add_listener
def preflight(environment, **_kwargs) -> None:
    """Prove the stub is actually serving before any load is generated.

    Fires on the master only. In distributed mode this event also reaches every
    worker, and four workers racing the same check would just be four real
    builds if the secret were wrong: the exact outcome being guarded against.
    """
    if isinstance(environment.runner, WorkerRunner):
        return

    if not SECRET:
        _abort(
            environment,
            "LOAD_TEST_SECRET is not set. Without it the server ignores the "
            "load-test header and every /chat request bills real OpenRouter "
            "tokens.",
        )
        return

    host = (environment.host or "").rstrip("/")
    if not host:
        _abort(environment, "no --host set; nothing to test")
        return

    try:
        res = requests.post(
            f"{host}/api/v1/chat",
            json=_turn_body(_PROMPTS[0]),
            headers=_headers(),
            stream=True,
            timeout=120,
        )
    except requests.RequestException as exc:
        _abort(environment, f"preflight /chat could not be reached: {exc}")
        return

    if res.status_code != 200:
        _abort(environment, f"preflight /chat returned {res.status_code}")
        return

    # Strict here, unlike the per-request check: the preflight runs against an
    # idle service with one request, so anything other than a clean stubbed
    # build means the run should not start, including a service error, which
    # at zero load is a broken deployment rather than saturation.
    verdict = _consume_stream(res, time.perf_counter(), {}).verdict
    if verdict is not _Stream.STUBBED:
        _abort(
            environment,
            f"preflight /chat came back as {verdict.name}, not STUBBED. The "
            "secret is wrong, LOAD_TEST_SECRET is unset on the server, or the "
            "worker running the turn did not receive the flag. If it was "
            "UNSTUBBED, real tokens were spent on this one request; stopping "
            "before the run multiplies that.",
        )
        return

    logger.info("preflight OK. %s is serving stubbed builds", host)


class _Turn:
    """What one /chat stream showed. Timings are ms from the request."""

    def __init__(self) -> None:
        self.first_progress_ms: float | None = None
        self.first_text_ms: float | None = None
        self.total_ms = 0.0
        self.delivered = False  # a build, case picker or system offer arrived
        self.errored = False  # an assistant-stream error line
        self.dspy_stubbed = False  # case options carry the DSPy stub's reason
        self.case_options: dict | None = None  # the picker, if the turn paused
        self.state: dict = {}  # the conversation state after this turn
        self.verdict = _Stream.EMPTY


# State keys whose arrival means the turn produced its real payload, beyond text.
_DELIVERABLES = ("build", "case_options", "system_offer")


def _apply(state: dict, op: dict) -> None:
    """Apply one assistant-transport operation to a local copy of the state.

    The server is authoritative and the client mirrors it. A follow-up request
    (the case pick) has to send that mirror back, the same as the browser does.
    """
    path, value = op.get("path") or [], op.get("value")
    if not path:
        return
    node: Any = state
    for key in path[:-1]:
        node = node[int(key)] if isinstance(node, list) else node.setdefault(key, {})
    last = path[-1]
    if isinstance(node, list):
        index = int(last)
        node.extend([None] * (index + 1 - len(node)))
        node[index] = (
            (node[index] or "") + value if op.get("type") == "append-text" else value
        )
    else:
        node[last] = (
            (node.get(last) or "") + value if op.get("type") == "append-text" else value
        )


def _consume_stream(response, started: float, state: dict) -> _Turn:
    """Drain one /chat assistant-transport stream and classify it.

    Two timings are worth watching, and neither is the HTTP response time
    Locust records on its own (that is headers, which the server sends at once):

      * worker pickup: the first ["pipeline"] update, i.e. a worker has picked
        the turn up. Under load this is the queue: Pub/Sub, KEDA scale-out and
        the worker's concurrency ceiling all show up here first. On a first
        turn it also includes profile extraction, one LLM call that runs before
        the first update (LOAD_TEST_STUB_DSPY_MS under the stub, 2s by
        default), so read its growth rather than its floor. On a case pick it
        is the queue alone.
      * first text: the first assistant text.

    The full stream mostly measures how long the stub chose to take, which says
    little about the service, for the same reason the server excludes streaming
    duration from its own request histogram.
    """
    turn = _Turn()
    turn.state = json.loads(json.dumps(state))  # the request's base, deep-copied
    parts: list[str] = []

    def now() -> float:
        return (time.perf_counter() - started) * 1000

    try:
        for line in response.iter_lines(decode_unicode=True):
            if not line:
                continue  # keepalive
            if line.startswith("3:"):
                # assistant-stream's error chunk: the run itself raised.
                turn.errored = True
                continue
            if not line.startswith("aui-state:"):
                continue
            try:
                ops = json.loads(line[len("aui-state:") :])
            except ValueError:
                continue
            for op in ops if isinstance(ops, list) else []:
                _apply(turn.state, op)
                path = op.get("path") or []
                value = op.get("value")
                if op.get("type") == "append-text":
                    if turn.first_text_ms is None:
                        turn.first_text_ms = now()
                    parts.append(value if isinstance(value, str) else "")
                elif path == ["pipeline"] and value:
                    if turn.first_progress_ms is None:
                        turn.first_progress_ms = now()
                elif path and path[-1] in _DELIVERABLES and value:
                    turn.delivered = True
                    if path[-1] == "case_options" and isinstance(value, dict):
                        turn.case_options = value
                        turn.dspy_stubbed = turn.dspy_stubbed or any(
                            isinstance(o, dict) and o.get("reason") == _DSPY_STUB_REASON
                            for o in value.get("options") or []
                        )
    finally:
        # An early exit leaves the connection mid-body, where urllib3 cannot
        # return it to the pool; without this the run leaks a socket per turn.
        response.close()

    turn.total_ms = now()
    reply = "".join(parts)
    if _STUB_MARKER in reply or turn.dspy_stubbed:
        # Checked first, and it wins: a stubbed turn that went on to hit an
        # error is still a turn that spent nothing, which is the only question
        # this verdict is used to answer.
        turn.verdict = _Stream.STUBBED
    elif turn.errored or any(marker in reply for marker in _SERVICE_ERRORS):
        turn.verdict = _Stream.SERVICE_ERROR
    elif not parts:
        turn.verdict = _Stream.EMPTY
    else:
        turn.verdict = _Stream.UNSTUBBED
    return turn


class ChatUser(HttpUser):
    """The expensive path: one new conversation per iteration, built to the end.

    Two requests, as a real user makes them. The first runs profile extraction
    and the component ladder and pauses at the case picker; the second picks
    the first case, which resumes the paused build (fans, validation) and writes
    the session to Postgres. Stopping after the first would leave that half,
    and every paused build it creates, untested.

    Ramp rather than slam. builder's HPA needs 60-120s to schedule a pod on
    Autopilot, so a spawn rate that reaches the target in seconds measures cold
    start, not steady-state capacity. Spawn rate 1/s is the right dial in the
    web UI.
    """

    weight = 1
    wait_time = between(2, 5)

    @task
    def chat(self) -> None:
        first = self._turn(_turn_body(_PROMPTS[self.chat_i()]), label="")
        if first is None or first.case_options is None:
            # Delivered a build outright (a locked case, a system offer) or
            # already failed and recorded why. Either way, nothing to pick.
            return
        options = first.case_options.get("options") or []
        if not options:
            return
        self._turn(
            {
                "conversation_id": None,
                "state": first.state,
                "commands": [
                    {
                        "type": "select-case",
                        "token": first.case_options.get("token"),
                        "caseName": options[0].get("name"),
                    }
                ],
            },
            label=" case pick",
        )

    def _turn(self, body: dict, label: str) -> _Turn | None:
        """POST one turn, classify its stream, and record it. None on failure."""
        started = time.perf_counter()

        with self.client.post(
            "/api/v1/chat",
            json=body,
            headers=_headers(),
            # stream=True is what makes the recorded response time meaningful:
            # requests returns as soon as the headers land, and Locust knows not
            # to touch .content on a streamed response, so this entry is time to
            # first byte rather than time to the end of the stream.
            stream=True,
            catch_response=True,
            name=f"POST /api/v1/chat{label} [headers]",
            timeout=180,
        ) as res:
            if res.status_code != 200:
                res.failure(f"HTTP {res.status_code}")
                return None

            try:
                turn = _consume_stream(res, started, body["state"])
            except Exception as exc:
                res.failure(f"stream aborted: {exc}")
                return None

            # Absence of the stub marker is ambiguous, and the two readings call
            # for opposite responses. A service error message costs nothing and
            # is exactly what a saturation test is trying to provoke; a real
            # model's answer costs money and must stop the run. Treating them
            # alike made the load test abort itself at the moment it started
            # measuring the thing it was pointed at.
            if turn.verdict is _Stream.SERVICE_ERROR:
                res.failure("build did not start (server fallback message)")
                return None
            if turn.verdict is _Stream.EMPTY:
                # No assistant text at all. No LM was reached, so nothing was
                # spent: a failed request, not a cost incident.
                res.failure("stream produced no assistant text")
                return None
            if turn.verdict is _Stream.UNSTUBBED:
                res.failure("served by a REAL model. See abort below")
                _abort(
                    self.environment,
                    "a /chat response carried model output with no stub marker "
                    "and no known service-error text. The run was billing real "
                    "OpenRouter tokens; stopping now.",
                )
                return None
            if not turn.delivered:
                # Stubbed, but no build or case picker: the turn took the
                # question-asking path instead of building, so the expensive path
                # is not what is being measured. See _BRANCH_FIELDS in
                # backend/app/core/loadtest_stubs.py.
                res.failure("stubbed turn delivered no build (elicitation path?)")
                return None

            res.success()

        # Reported as their own entries so the UI charts them next to the HTTP
        # timings instead of hiding them inside one averaged number.
        if turn.first_progress_ms is not None:
            self._fire(f"/api/v1/chat{label} [worker pickup]", turn.first_progress_ms)
        if turn.first_text_ms is not None:
            self._fire(f"/api/v1/chat{label} [first text]", turn.first_text_ms)
        self._fire(f"/api/v1/chat{label} [full turn]", turn.total_ms)
        return turn

    def chat_i(self) -> int:
        # Cheap round-robin over the prompt list; random would cluster.
        self._i = getattr(self, "_i", -1) + 1
        return self._i % len(_PROMPTS)

    def _fire(self, name: str, response_time_ms: float) -> None:
        self.environment.events.request.fire(
            request_type="STREAM",
            name=name,
            response_time=response_time_ms,
            response_length=0,
            exception=None,
            context={},
        )


class BrowseUser(HttpUser):
    """Cheap concurrent reads, as steady background load.

    Weighted well above ChatUser because that is the real traffic shape: most
    sessions browse listings and never start a build. Without it the chat
    numbers describe a service under a load nobody generates.
    """

    weight = 4
    wait_time = between(1, 3)

    @task(3)
    def listings(self) -> None:
        self.client.get(
            f"{COMMERCE_URL}/api/v1/listings/",
            name="GET /api/v1/listings/",
            headers=_headers(),
        )

    @task(1)
    def healthz(self) -> None:
        # Hits builder directly. Also the canary for whether the pods being
        # scaled out by the HPA are actually reaching Ready.
        self.client.get("/api/v1/healthz", name="GET /api/v1/healthz")
