"""Locust load test for the builder /chat endpoint and the commerce read paths.

COST SAFETY. Every request carries X-Palladium-Load-Test, which routes the turn
into stub LMs. See backend/app/core/loadtest.py. Without a matching
LOAD_TEST_SECRET on the server the header is ignored and the run makes REAL
OpenRouter calls, one per build step per simulated user. Two independent guards
exist so that cannot happen quietly:

  * a preflight in on_test_start, which refuses to start the run at all, and
  * a per-response check on every /chat call, which aborts the run mid-flight.

The second is not redundant. The preflight only proves the secret was good at
t=0; a rotation, a worker rollout onto an image without the stub, or a Pub/Sub
message that lost the flag would all start spending money after the run began.

WHY IT LIVES HERE and not in scripts/: this file is mounted into the Locust
pods as a ConfigMap generated by ./kustomization.yaml, and kustomize refuses to
read files above its own directory. Keeping it beside the manifests is what
makes `kubectl apply -k deploy/loadtest` a single self-contained command.

Run in-cluster, the normal way:
    kubectl apply -k deploy/loadtest
    kubectl -n palladium port-forward svc/locust-master 8089:8089

Run locally against a dev server:
    LOAD_TEST_SECRET=... COMMERCE_URL=http://localhost:8080 \
      locust -f deploy/loadtest/locustfile.py --host http://localhost:8000
"""

from __future__ import annotations

import json
import logging
import os
import time
from enum import Enum, auto

import gevent
import requests
from locust import HttpUser, between, events, task
from locust.runners import WorkerRunner

logger = logging.getLogger(__name__)

SECRET = os.environ.get("LOAD_TEST_SECRET", "")

# commerce is a second Service, so its calls go out as absolute URLs rather than
# through the user's base host. Deliberate: --host is what the web UI's Host
# field edits, and that field should mean "the builder deployment under test".
COMMERCE_URL = os.environ.get("COMMERCE_URL", "http://commerce").rstrip("/")

# ONE WORD, on purpose. The stub streams its reply word by word
# (loadtest_stubs._stream_chunks splits on spaces), so each SSE frame carries a
# single token and any multi-word marker is split across two frames and never
# matches. "stubbed" is the first distinctive word of the stub's canned text.
_STUB_MARKER = "stubbed"

# The server's own fallback texts, from routes/chat.py and turn_runner.py. These
# arrive as ordinary token frames, so without matching them explicitly a
# saturated backend is indistinguishable from a real model answering, and the
# cost guard would abort the run exactly when the load test got interesting.
# Matched on a distinctive fragment rather than the full string, which carries
# leading newlines and trailing punctuation.
_SERVICE_ERRORS = (
    "That build didn't start",
    "Lost the connection to the build service",
    "Something went wrong generating your recommendation",
)


class _Stream(Enum):
    """What produced a /chat stream. Drives cost safety, so it is explicit
    rather than a bool: "not the stub" covers both a free error message and an
    expensive real completion, and those are not the same event."""

    EMPTY = auto()  # no token frames at all
    STUBBED = auto()  # the stub LM. The expected case
    SERVICE_ERROR = auto()  # a server fallback message; nothing was spent
    UNSTUBBED = auto()  # real model output; money is being spent


# Varied enough that profile extraction sees different inputs, short enough that
# the request body is not itself the thing being measured.
_PROMPTS = [
    "I want a gaming PC for about $1500",
    "Build me a video editing workstation under $2500",
    "Cheapest machine that can run local LLMs, budget $2000",
    "Quiet small-form-factor PC for software development, around $1200",
]

# Latches so an abort fires once rather than once per simulated user.
_aborted = False


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "X-Palladium-Load-Test": SECRET,
    }


def _abort(environment, message: str) -> None:
    """Stop the whole run, loudly, without spending anything further."""
    global _aborted
    if _aborted:
        return
    _aborted = True

    logger.critical("ABORTING LOAD TEST: %s", message)
    # Non-zero exit for headless/CI runs. Ignored by the web UI, harmless there.
    environment.process_exit_code = 1

    if environment.runner is None:
        return
    # Deferred by a greenlet rather than called inline: quit() tears down the
    # runner that is currently executing this handler, and doing that from
    # inside its own event dispatch deadlocks. spawn_later(0) runs it on the
    # next gevent turn, once the handler has returned.
    #
    # In-cluster this exits the master process and Kubernetes restarts the pod,
    # which comes back to an idle web UI. That is the intended outcome: no load
    # is running, and the reason is in `kubectl logs`.
    gevent.spawn_later(0, environment.runner.quit)


@events.test_start.add_listener
def preflight(environment, **_kwargs) -> None:
    """Prove the stub is actually serving before any load is generated.

    Fires on the master only. In distributed mode this event also reaches every
    worker, and four workers racing the same check would just be four real
    builds if the secret were wrong: the exact outcome being guarded against.
    """
    if isinstance(environment.runner, WorkerRunner):
        return

    if not SECRET:
        _abort(
            environment,
            "LOAD_TEST_SECRET is not set. Without it the server ignores the "
            "load-test header and every /chat request bills real OpenRouter "
            "tokens.",
        )
        return

    host = (environment.host or "").rstrip("/")
    if not host:
        _abort(environment, "no --host set; nothing to test")
        return

    try:
        res = requests.post(
            f"{host}/api/v1/chat",
            json={"messages": [{"role": "user", "content": "hello"}]},
            headers=_headers(),
            stream=True,
            timeout=120,
        )
    except requests.RequestException as exc:
        _abort(environment, f"preflight /chat could not be reached: {exc}")
        return

    if res.status_code != 200:
        _abort(environment, f"preflight /chat returned {res.status_code}")
        return

    # Strict here, unlike the per-request check: the preflight runs against an
    # idle service with one request, so anything other than a clean stubbed
    # build means the run should not start, including a service error, which
    # at zero load is a broken deployment rather than saturation.
    _, _, verdict = _consume_sse(res, time.perf_counter())
    if verdict is not _Stream.STUBBED:
        _abort(
            environment,
            f"preflight /chat came back as {verdict.name}, not STUBBED. The "
            "secret is wrong, LOAD_TEST_SECRET is unset on the server, or the "
            "worker running the turn did not receive the flag. If it was "
            "UNSTUBBED, real tokens were spent on this one request; stopping "
            "before the run multiplies that.",
        )
        return

    logger.info("preflight OK. %s is serving stubbed builds", host)


def _consume_sse(response, started: float) -> tuple[float, float, _Stream]:
    """Drain one /chat SSE stream.

    Returns (ms to first token, ms to [DONE], what produced the stream).

    Time to first token is the number worth watching. Total duration mostly
    measures how long the stub chose to stream for, which says nothing about
    the health of the service: the same reason the server excludes streaming
    duration from its own request histogram.
    """
    first_token_ms: float | None = None
    # Classified from the assembled reply rather than frame by frame. SSE
    # framing is not something a marker can rely on: the stub emits one word per
    # frame, so every multi-word phrase below is split across several and
    # matches none of them individually. That is the same mistake the k6 script
    # this replaced had baked in.
    parts: list[str] = []

    try:
        for line in response.iter_lines(decode_unicode=True):
            # Blank separators between frames, and ": ping" keepalive comments
            # the relay sends during the long silent stretch while DSPy runs.
            if not line or not line.startswith("data:"):
                continue

            data = line[len("data:") :].strip()
            if data == "[DONE]":
                break

            try:
                event = json.loads(data)
            except ValueError:
                continue

            # The first frame is a {"type": "turn"} control event carrying the
            # turn id, not content. Timing to that would measure the dispatch,
            # not the model.
            if event.get("type") != "token":
                continue

            if first_token_ms is None:
                first_token_ms = (time.perf_counter() - started) * 1000

            parts.append(event.get("text", ""))
    finally:
        # An early break leaves the connection mid-body, where urllib3 cannot
        # return it to the pool; without this the run leaks a socket per turn.
        response.close()

    reply = "".join(parts)
    if not parts:
        verdict = _Stream.EMPTY
    elif _STUB_MARKER in reply:
        # Checked first, and it wins: a stubbed turn that went on to hit an
        # error is still a turn that spent nothing, which is the only question
        # this verdict is used to answer.
        verdict = _Stream.STUBBED
    elif any(marker in reply for marker in _SERVICE_ERRORS):
        verdict = _Stream.SERVICE_ERROR
    else:
        verdict = _Stream.UNSTUBBED

    total_ms = (time.perf_counter() - started) * 1000
    return (
        (first_token_ms if first_token_ms is not None else total_ms),
        total_ms,
        verdict,
    )


class ChatUser(HttpUser):
    """The expensive path: one streamed build per iteration.

    Ramp rather than slam. builder's HPA needs 60-120s to schedule a pod on
    Autopilot, so a spawn rate that reaches the target in seconds measures cold
    start, not steady-state capacity. Spawn rate 1/s is the right dial in the
    web UI.
    """

    weight = 1
    wait_time = between(2, 5)

    @task
    def chat(self) -> None:
        started = time.perf_counter()

        with self.client.post(
            "/api/v1/chat",
            json={"messages": [{"role": "user", "content": _PROMPTS[self.chat_i()]}]},
            headers=_headers(),
            # stream=True is what makes the recorded response time meaningful:
            # requests returns as soon as the headers land, and Locust knows not
            # to touch .content on a streamed response, so this entry is time to
            # first byte rather than time to the end of the stream.
            stream=True,
            catch_response=True,
            name="POST /api/v1/chat [headers]",
            timeout=120,
        ) as res:
            if res.status_code != 200:
                res.failure(f"HTTP {res.status_code}")
                return

            try:
                first_token_ms, total_ms, verdict = _consume_sse(res, started)
            except Exception as exc:
                res.failure(f"stream aborted: {exc}")
                return

            # Absence of the stub marker is ambiguous, and the two readings call
            # for opposite responses. A service error message costs nothing and
            # is exactly what a saturation test is trying to provoke; a real
            # model's answer costs money and must stop the run. Treating them
            # alike made the load test abort itself at the moment it started
            # measuring the thing it was pointed at.
            if verdict is _Stream.SERVICE_ERROR:
                res.failure("build did not start (server fallback message)")
                return
            if verdict is _Stream.EMPTY:
                # No token frames at all. No LM was reached, so nothing was
                # spent: a failed request, not a cost incident.
                res.failure("stream produced no tokens")
                return
            if verdict is _Stream.UNSTUBBED:
                res.failure("served by a REAL model. See abort below")
                _abort(
                    self.environment,
                    "a /chat response carried model output with no stub marker "
                    "and no known service-error text. The run was billing real "
                    "OpenRouter tokens; stopping now.",
                )
                return

            res.success()

        # Reported as their own entries so the UI charts them next to the HTTP
        # timings instead of hiding them inside one averaged number.
        self._fire("/api/v1/chat [first token]", first_token_ms)
        self._fire("/api/v1/chat [full stream]", total_ms)

    def chat_i(self) -> int:
        # Cheap round-robin over the prompt list; random would cluster.
        self._i = getattr(self, "_i", -1) + 1
        return self._i % len(_PROMPTS)

    def _fire(self, name: str, response_time_ms: float) -> None:
        self.environment.events.request.fire(
            request_type="SSE",
            name=name,
            response_time=response_time_ms,
            response_length=0,
            exception=None,
            context={},
        )


class BrowseUser(HttpUser):
    """Cheap concurrent reads, as steady background load.

    Weighted well above ChatUser because that is the real traffic shape: most
    sessions browse listings and never start a build. Without it the chat
    numbers describe a service under a load nobody generates.
    """

    weight = 4
    wait_time = between(1, 3)

    @task(3)
    def listings(self) -> None:
        self.client.get(
            f"{COMMERCE_URL}/api/v1/listings/",
            name="GET /api/v1/listings/",
            headers=_headers(),
        )

    @task(1)
    def healthz(self) -> None:
        # Hits builder directly. Also the canary for whether the pods being
        # scaled out by the HPA are actually reaching Ready.
        self.client.get("/api/v1/healthz", name="GET /api/v1/healthz")
