/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUnderconstructionRouteImport } from './routes/_layout/underconstruction'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutNewbuildRouteImport } from './routes/_layout/newbuild'
import { Route as LayoutGuidesRouteImport } from './routes/_layout/guides'
import { Route as LayoutFindbuilderRouteImport } from './routes/_layout/findbuilder'
import { Route as LayoutBuildhistoryRouteImport } from './routes/_layout/buildhistory'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUnderconstructionRoute = LayoutUnderconstructionRouteImport.update({
  id: '/underconstruction',
  path: '/underconstruction',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewbuildRoute = LayoutNewbuildRouteImport.update({
  id: '/newbuild',
  path: '/newbuild',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuidesRoute = LayoutGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFindbuilderRoute = LayoutFindbuilderRouteImport.update({
  id: '/findbuilder',
  path: '/findbuilder',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildhistoryRoute = LayoutBuildhistoryRouteImport.update({
  id: '/buildhistory',
  path: '/buildhistory',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/buildhistory': typeof LayoutBuildhistoryRoute
  '/findbuilder': typeof LayoutFindbuilderRoute
  '/guides': typeof LayoutGuidesRoute
  '/newbuild': typeof LayoutNewbuildRoute
  '/settings': typeof LayoutSettingsRoute
  '/underconstruction': typeof LayoutUnderconstructionRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/buildhistory': typeof LayoutBuildhistoryRoute
  '/findbuilder': typeof LayoutFindbuilderRoute
  '/guides': typeof LayoutGuidesRoute
  '/newbuild': typeof LayoutNewbuildRoute
  '/settings': typeof LayoutSettingsRoute
  '/underconstruction': typeof LayoutUnderconstructionRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/buildhistory': typeof LayoutBuildhistoryRoute
  '/_layout/findbuilder': typeof LayoutFindbuilderRoute
  '/_layout/guides': typeof LayoutGuidesRoute
  '/_layout/newbuild': typeof LayoutNewbuildRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/underconstruction': typeof LayoutUnderconstructionRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/buildhistory'
    | '/findbuilder'
    | '/guides'
    | '/newbuild'
    | '/settings'
    | '/underconstruction'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/buildhistory'
    | '/findbuilder'
    | '/guides'
    | '/newbuild'
    | '/settings'
    | '/underconstruction'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/buildhistory'
    | '/_layout/findbuilder'
    | '/_layout/guides'
    | '/_layout/newbuild'
    | '/_layout/settings'
    | '/_layout/underconstruction'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/underconstruction': {
      id: '/_layout/underconstruction'
      path: '/underconstruction'
      fullPath: '/underconstruction'
      preLoaderRoute: typeof LayoutUnderconstructionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/newbuild': {
      id: '/_layout/newbuild'
      path: '/newbuild'
      fullPath: '/newbuild'
      preLoaderRoute: typeof LayoutNewbuildRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guides': {
      id: '/_layout/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof LayoutGuidesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/findbuilder': {
      id: '/_layout/findbuilder'
      path: '/findbuilder'
      fullPath: '/findbuilder'
      preLoaderRoute: typeof LayoutFindbuilderRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/buildhistory': {
      id: '/_layout/buildhistory'
      path: '/buildhistory'
      fullPath: '/buildhistory'
      preLoaderRoute: typeof LayoutBuildhistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBuildhistoryRoute: typeof LayoutBuildhistoryRoute
  LayoutFindbuilderRoute: typeof LayoutFindbuilderRoute
  LayoutGuidesRoute: typeof LayoutGuidesRoute
  LayoutNewbuildRoute: typeof LayoutNewbuildRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUnderconstructionRoute: typeof LayoutUnderconstructionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBuildhistoryRoute: LayoutBuildhistoryRoute,
  LayoutFindbuilderRoute: LayoutFindbuilderRoute,
  LayoutGuidesRoute: LayoutGuidesRoute,
  LayoutNewbuildRoute: LayoutNewbuildRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUnderconstructionRoute: LayoutUnderconstructionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
